---
title: Two-Rate Proprioception - How Quickly Does Proprioception Recalibrate And Is
  It Related To The Two-Rate Model Of Motor Learning
author:
- Jennifer E. Ruttle
- Bernard Marius 't Hart
- Denise Y.P. Henriques
csl: lit/plos-one.csl
output:
<<<<<<< HEAD:TwoRateProprioception.Rmd
  word_document: default
  pdf_document: default
  html_notebook: default
=======
  html_notebook: default
  word_document: default
  pdf_document: default
  html_document: null
>>>>>>> bc0aca84b7292c5aca7ce5dc592b06333d6d64b1:TwoRateProprioception_Notes.Rmd
link-citations: yes
bibliography: lit/bibliography.bib
---

# Overview

We have previously found that proprioception recalibrates within 6 trials, whereas visuomotor adaptation takes longer to saturate [@Ruttle2016; @Ruttle2018].

In this project we set out to investigate 1) exactly how quickly proprioception recalibrates, 2) to disentangle it from the updating of predicted sensory consequences, and 3) to see if it matches implicit learning that should follow the slow process [@McDougle2015] in the two-rate model [@Smith2006].

## Trial types

To do all this we use a trial-by-trial approach, that is: one reach-training trial is followed by one of various "measurement" trials: passive localization, active localization or no-cursor reaches (all of them explained below). As a control we also had people pause for a short bit instead. There were four groups of participants and each did one of the four "measurement" trials exclusively. With one exception, the pause and no-cursor group also did a set of localization trials before and after the regular paradigm also done by the other groups.

The first of each pair of trials is always one of these, both appear for every participant:
- reach training
- error-clamp

The second of each pair of trials is then one of these:
- passive localization (only proprioception)
- active localization (proprioception + prediction)
- no-cursor reach (classic measure of motor learning)
- pause (control)

These four trial types define the four paradigms, that is, each of the participants in the four groups only get 1 of these trial types throughout. However, the no-cursor group and pause group do get some passive localization before training, and after completion of the whole paradigm.

By comparing the trial-by-trial changes in the four paradigms, we can investigate the time-course of all these processes in more detail than we previously have.

## Figures

Here is a list of planned figures with their potential message:

- Fig 1: A) setup, B) reach training + targets, C) localization + points, D) no-cursor + targets (illustrate the hardware and trial types, not done in R)
- Fig 2: paradigm, four phases (aligned, rotated, reversed, error-clamped), plus extra localization phases (illustrate the main paradigm... add expected model fit?)
- Fig 3: A,B,C,D) one subplot for each group showing reach deviations in the four main phases: individual traces, 95% confidence intervals, median (show quality of the data)
- Fig 4: A,B,C,D) one subplot for each group showing the median reach deviations in the four main phases, plus the two-rate model fit and it's fast and slow process (show quality of the fits)
- Fig 5: comparing reach deviations over time, (show differences between the groups, or should this go in a previous figure? seems it would get cluttered)
- Fig 6: A) localization throughout for the two localization groups, B) localization shift in the pause and no-cursor group, C) speed of localization shift, D/E) localization shift with the two processes for each group (show the incredible speed of localization shifts and how non-matching the slow but also the fast process are)
- Fig 7: alternative models of localization? (20% model works reasonably well... even better than giving localization it's own two- or one-rate model)
- Fig 8: A) time course of no-cursor changes (no-cursor could reflect a watered down version of the slow process?)

## Two-Rate model

In the two-rate model, the motor output X at trial t, $X_t$ is simply the added output of the slow and fast process at trial t:

<<<<<<< HEAD:TwoRateProprioception.Rmd
\begin{equation}
\label{tworate-total}
X_t = S_t + F_t
\end{equation}

The output of the slow process on the next trial (t+1) is determined by the error on the previous trial multiplied by a learning rate L, and the output on the previous trial multiplied by a retention rate R:

\begin{equation}
\label{tworate-slow}
S_{t+1} = (L^s \cdot E_t) + (R^s \cdot S_t)
\end{equation}

Similarly, the fast process has it's own learning rate and retention rate:

\begin{equation}
\label{tworate-fast}
F_{t+1} = (L^f \cdot E_t) + (R^f \cdot F_t)
\end{equation}
=======
[1] $X_t = S_t + F_t$ \label{tworate-total}

The output of the slow process on the next trial (t+1) is determined by the error on the previous trial multiplied by a learning rate L, and the output on the previous trial multiplied by a retention rate R:

[2] $S_{t+1} = L^s \cdot E_t + R^s \cdot S_t$ \label{tworate-slow}

Similarly, the fast process has it's own learning rate and retention rate:

[3] $F_{t+1} = L^f \cdot E_t + R^f \cdot F_t$ \label{tworate-fast}
>>>>>>> bc0aca84b7292c5aca7ce5dc592b06333d6d64b1:TwoRateProprioception_Notes.Rmd

The four parameters $L^s$, $R^s$, $L^f$ and $R^f$ will be fit so that $X_t$ matches the recorded reach deviations optimally according to a least-squared error algorithm. They should each fall within the range [0,1]. To ensure that the fast process learns faster than the slow process but also forgets faster than the slow process the model is further constrained by requiring that $L^s < L^f$ and $R^s > R^f$.


# References